// Code generated by go-swagger; DO NOT EDIT.

package transfer_credit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new transfer credit API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for transfer credit API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ResellerTransferCreditPut transfers credit

Transfer Credit
*/
func (a *Client) ResellerTransferCreditPut(params *ResellerTransferCreditPutParams, authInfo runtime.ClientAuthInfoWriter) (*ResellerTransferCreditPutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewResellerTransferCreditPutParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "ResellerTransferCreditPut",
		Method:             "PUT",
		PathPattern:        "/reseller/transfer-credit",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ResellerTransferCreditPutReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ResellerTransferCreditPutOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
