// Code generated by go-swagger; DO NOT EDIT.

package email_delivery_receipt_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEmailDeliveryReceiptAutomationGetParams creates a new EmailDeliveryReceiptAutomationGetParams object
// with the default values initialized.
func NewEmailDeliveryReceiptAutomationGetParams() *EmailDeliveryReceiptAutomationGetParams {
	var ()
	return &EmailDeliveryReceiptAutomationGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmailDeliveryReceiptAutomationGetParamsWithTimeout creates a new EmailDeliveryReceiptAutomationGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmailDeliveryReceiptAutomationGetParamsWithTimeout(timeout time.Duration) *EmailDeliveryReceiptAutomationGetParams {
	var ()
	return &EmailDeliveryReceiptAutomationGetParams{

		timeout: timeout,
	}
}

// NewEmailDeliveryReceiptAutomationGetParamsWithContext creates a new EmailDeliveryReceiptAutomationGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmailDeliveryReceiptAutomationGetParamsWithContext(ctx context.Context) *EmailDeliveryReceiptAutomationGetParams {
	var ()
	return &EmailDeliveryReceiptAutomationGetParams{

		Context: ctx,
	}
}

// NewEmailDeliveryReceiptAutomationGetParamsWithHTTPClient creates a new EmailDeliveryReceiptAutomationGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmailDeliveryReceiptAutomationGetParamsWithHTTPClient(client *http.Client) *EmailDeliveryReceiptAutomationGetParams {
	var ()
	return &EmailDeliveryReceiptAutomationGetParams{
		HTTPClient: client,
	}
}

/*EmailDeliveryReceiptAutomationGetParams contains all the parameters to send to the API endpoint
for the email delivery receipt automation get operation typically these are written to a http.Request
*/
type EmailDeliveryReceiptAutomationGetParams struct {

	/*ReceiptRuleID
	  Receipt rule id

	*/
	ReceiptRuleID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) WithTimeout(timeout time.Duration) *EmailDeliveryReceiptAutomationGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) WithContext(ctx context.Context) *EmailDeliveryReceiptAutomationGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) WithHTTPClient(client *http.Client) *EmailDeliveryReceiptAutomationGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReceiptRuleID adds the receiptRuleID to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) WithReceiptRuleID(receiptRuleID int32) *EmailDeliveryReceiptAutomationGetParams {
	o.SetReceiptRuleID(receiptRuleID)
	return o
}

// SetReceiptRuleID adds the receiptRuleId to the email delivery receipt automation get params
func (o *EmailDeliveryReceiptAutomationGetParams) SetReceiptRuleID(receiptRuleID int32) {
	o.ReceiptRuleID = receiptRuleID
}

// WriteToRequest writes these params to a swagger request
func (o *EmailDeliveryReceiptAutomationGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param receipt_rule_id
	if err := r.SetPathParam("receipt_rule_id", swag.FormatInt32(o.ReceiptRuleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
