// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNumbersBuyByDedicatedNumberPostParams creates a new NumbersBuyByDedicatedNumberPostParams object
// with the default values initialized.
func NewNumbersBuyByDedicatedNumberPostParams() *NumbersBuyByDedicatedNumberPostParams {
	var ()
	return &NumbersBuyByDedicatedNumberPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNumbersBuyByDedicatedNumberPostParamsWithTimeout creates a new NumbersBuyByDedicatedNumberPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNumbersBuyByDedicatedNumberPostParamsWithTimeout(timeout time.Duration) *NumbersBuyByDedicatedNumberPostParams {
	var ()
	return &NumbersBuyByDedicatedNumberPostParams{

		timeout: timeout,
	}
}

// NewNumbersBuyByDedicatedNumberPostParamsWithContext creates a new NumbersBuyByDedicatedNumberPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewNumbersBuyByDedicatedNumberPostParamsWithContext(ctx context.Context) *NumbersBuyByDedicatedNumberPostParams {
	var ()
	return &NumbersBuyByDedicatedNumberPostParams{

		Context: ctx,
	}
}

// NewNumbersBuyByDedicatedNumberPostParamsWithHTTPClient creates a new NumbersBuyByDedicatedNumberPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNumbersBuyByDedicatedNumberPostParamsWithHTTPClient(client *http.Client) *NumbersBuyByDedicatedNumberPostParams {
	var ()
	return &NumbersBuyByDedicatedNumberPostParams{
		HTTPClient: client,
	}
}

/*NumbersBuyByDedicatedNumberPostParams contains all the parameters to send to the API endpoint
for the numbers buy by dedicated number post operation typically these are written to a http.Request
*/
type NumbersBuyByDedicatedNumberPostParams struct {

	/*DedicatedNumber
	  Phone number to purchase

	*/
	DedicatedNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) WithTimeout(timeout time.Duration) *NumbersBuyByDedicatedNumberPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) WithContext(ctx context.Context) *NumbersBuyByDedicatedNumberPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) WithHTTPClient(client *http.Client) *NumbersBuyByDedicatedNumberPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDedicatedNumber adds the dedicatedNumber to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) WithDedicatedNumber(dedicatedNumber string) *NumbersBuyByDedicatedNumberPostParams {
	o.SetDedicatedNumber(dedicatedNumber)
	return o
}

// SetDedicatedNumber adds the dedicatedNumber to the numbers buy by dedicated number post params
func (o *NumbersBuyByDedicatedNumberPostParams) SetDedicatedNumber(dedicatedNumber string) {
	o.DedicatedNumber = dedicatedNumber
}

// WriteToRequest writes these params to a swagger request
func (o *NumbersBuyByDedicatedNumberPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dedicated_number
	if err := r.SetPathParam("dedicated_number", o.DedicatedNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
