// Code generated by go-swagger; DO NOT EDIT.

package countries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCountriesGetParams creates a new CountriesGetParams object
// with the default values initialized.
func NewCountriesGetParams() *CountriesGetParams {

	return &CountriesGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCountriesGetParamsWithTimeout creates a new CountriesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCountriesGetParamsWithTimeout(timeout time.Duration) *CountriesGetParams {

	return &CountriesGetParams{

		timeout: timeout,
	}
}

// NewCountriesGetParamsWithContext creates a new CountriesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCountriesGetParamsWithContext(ctx context.Context) *CountriesGetParams {

	return &CountriesGetParams{

		Context: ctx,
	}
}

// NewCountriesGetParamsWithHTTPClient creates a new CountriesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCountriesGetParamsWithHTTPClient(client *http.Client) *CountriesGetParams {

	return &CountriesGetParams{
		HTTPClient: client,
	}
}

/*CountriesGetParams contains all the parameters to send to the API endpoint
for the countries get operation typically these are written to a http.Request
*/
type CountriesGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the countries get params
func (o *CountriesGetParams) WithTimeout(timeout time.Duration) *CountriesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the countries get params
func (o *CountriesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the countries get params
func (o *CountriesGetParams) WithContext(ctx context.Context) *CountriesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the countries get params
func (o *CountriesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the countries get params
func (o *CountriesGetParams) WithHTTPClient(client *http.Client) *CountriesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the countries get params
func (o *CountriesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CountriesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
