// Code generated by go-swagger; DO NOT EDIT.

package contact

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListsContactsByListIDAndContactIDDeleteParams creates a new ListsContactsByListIDAndContactIDDeleteParams object
// with the default values initialized.
func NewListsContactsByListIDAndContactIDDeleteParams() *ListsContactsByListIDAndContactIDDeleteParams {
	var ()
	return &ListsContactsByListIDAndContactIDDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListsContactsByListIDAndContactIDDeleteParamsWithTimeout creates a new ListsContactsByListIDAndContactIDDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListsContactsByListIDAndContactIDDeleteParamsWithTimeout(timeout time.Duration) *ListsContactsByListIDAndContactIDDeleteParams {
	var ()
	return &ListsContactsByListIDAndContactIDDeleteParams{

		timeout: timeout,
	}
}

// NewListsContactsByListIDAndContactIDDeleteParamsWithContext creates a new ListsContactsByListIDAndContactIDDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewListsContactsByListIDAndContactIDDeleteParamsWithContext(ctx context.Context) *ListsContactsByListIDAndContactIDDeleteParams {
	var ()
	return &ListsContactsByListIDAndContactIDDeleteParams{

		Context: ctx,
	}
}

// NewListsContactsByListIDAndContactIDDeleteParamsWithHTTPClient creates a new ListsContactsByListIDAndContactIDDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListsContactsByListIDAndContactIDDeleteParamsWithHTTPClient(client *http.Client) *ListsContactsByListIDAndContactIDDeleteParams {
	var ()
	return &ListsContactsByListIDAndContactIDDeleteParams{
		HTTPClient: client,
	}
}

/*ListsContactsByListIDAndContactIDDeleteParams contains all the parameters to send to the API endpoint
for the lists contacts by list Id and contact Id delete operation typically these are written to a http.Request
*/
type ListsContactsByListIDAndContactIDDeleteParams struct {

	/*ContactID
	  Contact ID

	*/
	ContactID int32
	/*ListID
	  List ID

	*/
	ListID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) WithTimeout(timeout time.Duration) *ListsContactsByListIDAndContactIDDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) WithContext(ctx context.Context) *ListsContactsByListIDAndContactIDDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) WithHTTPClient(client *http.Client) *ListsContactsByListIDAndContactIDDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactID adds the contactID to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) WithContactID(contactID int32) *ListsContactsByListIDAndContactIDDeleteParams {
	o.SetContactID(contactID)
	return o
}

// SetContactID adds the contactId to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) SetContactID(contactID int32) {
	o.ContactID = contactID
}

// WithListID adds the listID to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) WithListID(listID int32) *ListsContactsByListIDAndContactIDDeleteParams {
	o.SetListID(listID)
	return o
}

// SetListID adds the listId to the lists contacts by list Id and contact Id delete params
func (o *ListsContactsByListIDAndContactIDDeleteParams) SetListID(listID int32) {
	o.ListID = listID
}

// WriteToRequest writes these params to a swagger request
func (o *ListsContactsByListIDAndContactIDDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contact_id
	if err := r.SetPathParam("contact_id", swag.FormatInt32(o.ContactID)); err != nil {
		return err
	}

	// path param list_id
	if err := r.SetPathParam("list_id", swag.FormatInt32(o.ListID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
