// Code generated by go-swagger; DO NOT EDIT.

package transactional_email

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/danikarik/clicksend-go/models"
)

// NewEmailSendPostParams creates a new EmailSendPostParams object
// with the default values initialized.
func NewEmailSendPostParams() *EmailSendPostParams {
	var ()
	return &EmailSendPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEmailSendPostParamsWithTimeout creates a new EmailSendPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEmailSendPostParamsWithTimeout(timeout time.Duration) *EmailSendPostParams {
	var ()
	return &EmailSendPostParams{

		timeout: timeout,
	}
}

// NewEmailSendPostParamsWithContext creates a new EmailSendPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewEmailSendPostParamsWithContext(ctx context.Context) *EmailSendPostParams {
	var ()
	return &EmailSendPostParams{

		Context: ctx,
	}
}

// NewEmailSendPostParamsWithHTTPClient creates a new EmailSendPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEmailSendPostParamsWithHTTPClient(client *http.Client) *EmailSendPostParams {
	var ()
	return &EmailSendPostParams{
		HTTPClient: client,
	}
}

/*EmailSendPostParams contains all the parameters to send to the API endpoint
for the email send post operation typically these are written to a http.Request
*/
type EmailSendPostParams struct {

	/*Email
	  Email model

	*/
	Email models.Email

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the email send post params
func (o *EmailSendPostParams) WithTimeout(timeout time.Duration) *EmailSendPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the email send post params
func (o *EmailSendPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the email send post params
func (o *EmailSendPostParams) WithContext(ctx context.Context) *EmailSendPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the email send post params
func (o *EmailSendPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the email send post params
func (o *EmailSendPostParams) WithHTTPClient(client *http.Client) *EmailSendPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the email send post params
func (o *EmailSendPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the email send post params
func (o *EmailSendPostParams) WithEmail(email models.Email) *EmailSendPostParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the email send post params
func (o *EmailSendPostParams) SetEmail(email models.Email) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *EmailSendPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Email); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
