// Code generated by go-swagger; DO NOT EDIT.

package account_recharge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/danikarik/clicksend-go/models"
)

// NewRechargeCreditCardPutParams creates a new RechargeCreditCardPutParams object
// with the default values initialized.
func NewRechargeCreditCardPutParams() *RechargeCreditCardPutParams {
	var ()
	return &RechargeCreditCardPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRechargeCreditCardPutParamsWithTimeout creates a new RechargeCreditCardPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRechargeCreditCardPutParamsWithTimeout(timeout time.Duration) *RechargeCreditCardPutParams {
	var ()
	return &RechargeCreditCardPutParams{

		timeout: timeout,
	}
}

// NewRechargeCreditCardPutParamsWithContext creates a new RechargeCreditCardPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewRechargeCreditCardPutParamsWithContext(ctx context.Context) *RechargeCreditCardPutParams {
	var ()
	return &RechargeCreditCardPutParams{

		Context: ctx,
	}
}

// NewRechargeCreditCardPutParamsWithHTTPClient creates a new RechargeCreditCardPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRechargeCreditCardPutParamsWithHTTPClient(client *http.Client) *RechargeCreditCardPutParams {
	var ()
	return &RechargeCreditCardPutParams{
		HTTPClient: client,
	}
}

/*RechargeCreditCardPutParams contains all the parameters to send to the API endpoint
for the recharge credit card put operation typically these are written to a http.Request
*/
type RechargeCreditCardPutParams struct {

	/*CreditCard
	  CreditCard model

	*/
	CreditCard models.CreditCard

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the recharge credit card put params
func (o *RechargeCreditCardPutParams) WithTimeout(timeout time.Duration) *RechargeCreditCardPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recharge credit card put params
func (o *RechargeCreditCardPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recharge credit card put params
func (o *RechargeCreditCardPutParams) WithContext(ctx context.Context) *RechargeCreditCardPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recharge credit card put params
func (o *RechargeCreditCardPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recharge credit card put params
func (o *RechargeCreditCardPutParams) WithHTTPClient(client *http.Client) *RechargeCreditCardPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recharge credit card put params
func (o *RechargeCreditCardPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreditCard adds the creditCard to the recharge credit card put params
func (o *RechargeCreditCardPutParams) WithCreditCard(creditCard models.CreditCard) *RechargeCreditCardPutParams {
	o.SetCreditCard(creditCard)
	return o
}

// SetCreditCard adds the creditCard to the recharge credit card put params
func (o *RechargeCreditCardPutParams) SetCreditCard(creditCard models.CreditCard) {
	o.CreditCard = creditCard
}

// WriteToRequest writes these params to a swagger request
func (o *RechargeCreditCardPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.CreditCard); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
