// Code generated by go-swagger; DO NOT EDIT.

package email_to_sms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSMSEmailSMSStrippedStringGetParams creates a new SMSEmailSMSStrippedStringGetParams object
// with the default values initialized.
func NewSMSEmailSMSStrippedStringGetParams() *SMSEmailSMSStrippedStringGetParams {
	var ()
	return &SMSEmailSMSStrippedStringGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSMSEmailSMSStrippedStringGetParamsWithTimeout creates a new SMSEmailSMSStrippedStringGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSMSEmailSMSStrippedStringGetParamsWithTimeout(timeout time.Duration) *SMSEmailSMSStrippedStringGetParams {
	var ()
	return &SMSEmailSMSStrippedStringGetParams{

		timeout: timeout,
	}
}

// NewSMSEmailSMSStrippedStringGetParamsWithContext creates a new SMSEmailSMSStrippedStringGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSMSEmailSMSStrippedStringGetParamsWithContext(ctx context.Context) *SMSEmailSMSStrippedStringGetParams {
	var ()
	return &SMSEmailSMSStrippedStringGetParams{

		Context: ctx,
	}
}

// NewSMSEmailSMSStrippedStringGetParamsWithHTTPClient creates a new SMSEmailSMSStrippedStringGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSMSEmailSMSStrippedStringGetParamsWithHTTPClient(client *http.Client) *SMSEmailSMSStrippedStringGetParams {
	var ()
	return &SMSEmailSMSStrippedStringGetParams{
		HTTPClient: client,
	}
}

/*SMSEmailSMSStrippedStringGetParams contains all the parameters to send to the API endpoint
for the Sms email Sms stripped string get operation typically these are written to a http.Request
*/
type SMSEmailSMSStrippedStringGetParams struct {

	/*RuleID
	  Your rule id

	*/
	RuleID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) WithTimeout(timeout time.Duration) *SMSEmailSMSStrippedStringGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) WithContext(ctx context.Context) *SMSEmailSMSStrippedStringGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) WithHTTPClient(client *http.Client) *SMSEmailSMSStrippedStringGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRuleID adds the ruleID to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) WithRuleID(ruleID int32) *SMSEmailSMSStrippedStringGetParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the Sms email Sms stripped string get params
func (o *SMSEmailSMSStrippedStringGetParams) SetRuleID(ruleID int32) {
	o.RuleID = ruleID
}

// WriteToRequest writes these params to a swagger request
func (o *SMSEmailSMSStrippedStringGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rule_id
	if err := r.SetPathParam("rule_id", swag.FormatInt32(o.RuleID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
