// Code generated by go-swagger; DO NOT EDIT.

package subaccount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSubaccountsRegenAPIKeyBySubaccountIDPutParams creates a new SubaccountsRegenAPIKeyBySubaccountIDPutParams object
// with the default values initialized.
func NewSubaccountsRegenAPIKeyBySubaccountIDPutParams() *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	var ()
	return &SubaccountsRegenAPIKeyBySubaccountIDPutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubaccountsRegenAPIKeyBySubaccountIDPutParamsWithTimeout creates a new SubaccountsRegenAPIKeyBySubaccountIDPutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubaccountsRegenAPIKeyBySubaccountIDPutParamsWithTimeout(timeout time.Duration) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	var ()
	return &SubaccountsRegenAPIKeyBySubaccountIDPutParams{

		timeout: timeout,
	}
}

// NewSubaccountsRegenAPIKeyBySubaccountIDPutParamsWithContext creates a new SubaccountsRegenAPIKeyBySubaccountIDPutParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubaccountsRegenAPIKeyBySubaccountIDPutParamsWithContext(ctx context.Context) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	var ()
	return &SubaccountsRegenAPIKeyBySubaccountIDPutParams{

		Context: ctx,
	}
}

// NewSubaccountsRegenAPIKeyBySubaccountIDPutParamsWithHTTPClient creates a new SubaccountsRegenAPIKeyBySubaccountIDPutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSubaccountsRegenAPIKeyBySubaccountIDPutParamsWithHTTPClient(client *http.Client) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	var ()
	return &SubaccountsRegenAPIKeyBySubaccountIDPutParams{
		HTTPClient: client,
	}
}

/*SubaccountsRegenAPIKeyBySubaccountIDPutParams contains all the parameters to send to the API endpoint
for the subaccounts regen Api key by subaccount Id put operation typically these are written to a http.Request
*/
type SubaccountsRegenAPIKeyBySubaccountIDPutParams struct {

	/*SubaccountID
	  ID of subaccount to regenerate API key for

	*/
	SubaccountID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) WithTimeout(timeout time.Duration) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) WithContext(ctx context.Context) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) WithHTTPClient(client *http.Client) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubaccountID adds the subaccountID to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) WithSubaccountID(subaccountID int32) *SubaccountsRegenAPIKeyBySubaccountIDPutParams {
	o.SetSubaccountID(subaccountID)
	return o
}

// SetSubaccountID adds the subaccountId to the subaccounts regen Api key by subaccount Id put params
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) SetSubaccountID(subaccountID int32) {
	o.SubaccountID = subaccountID
}

// WriteToRequest writes these params to a swagger request
func (o *SubaccountsRegenAPIKeyBySubaccountIDPutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subaccount_id
	if err := r.SetPathParam("subaccount_id", swag.FormatInt32(o.SubaccountID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
