// Code generated by go-swagger; DO NOT EDIT.

package sms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSMSTemplatesGetParams creates a new SMSTemplatesGetParams object
// with the default values initialized.
func NewSMSTemplatesGetParams() *SMSTemplatesGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSTemplatesGetParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewSMSTemplatesGetParamsWithTimeout creates a new SMSTemplatesGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSMSTemplatesGetParamsWithTimeout(timeout time.Duration) *SMSTemplatesGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSTemplatesGetParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		timeout: timeout,
	}
}

// NewSMSTemplatesGetParamsWithContext creates a new SMSTemplatesGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSMSTemplatesGetParamsWithContext(ctx context.Context) *SMSTemplatesGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSTemplatesGetParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		Context: ctx,
	}
}

// NewSMSTemplatesGetParamsWithHTTPClient creates a new SMSTemplatesGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSMSTemplatesGetParamsWithHTTPClient(client *http.Client) *SMSTemplatesGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSTemplatesGetParams{
		Limit:      &limitDefault,
		Page:       &pageDefault,
		HTTPClient: client,
	}
}

/*SMSTemplatesGetParams contains all the parameters to send to the API endpoint
for the Sms templates get operation typically these are written to a http.Request
*/
type SMSTemplatesGetParams struct {

	/*Limit
	  Number of records per page

	*/
	Limit *int32
	/*Page
	  Page number

	*/
	Page *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Sms templates get params
func (o *SMSTemplatesGetParams) WithTimeout(timeout time.Duration) *SMSTemplatesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Sms templates get params
func (o *SMSTemplatesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Sms templates get params
func (o *SMSTemplatesGetParams) WithContext(ctx context.Context) *SMSTemplatesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Sms templates get params
func (o *SMSTemplatesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Sms templates get params
func (o *SMSTemplatesGetParams) WithHTTPClient(client *http.Client) *SMSTemplatesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Sms templates get params
func (o *SMSTemplatesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the Sms templates get params
func (o *SMSTemplatesGetParams) WithLimit(limit *int32) *SMSTemplatesGetParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the Sms templates get params
func (o *SMSTemplatesGetParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithPage adds the page to the Sms templates get params
func (o *SMSTemplatesGetParams) WithPage(page *int32) *SMSTemplatesGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the Sms templates get params
func (o *SMSTemplatesGetParams) SetPage(page *int32) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *SMSTemplatesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
