// Code generated by go-swagger; DO NOT EDIT.

package inbound_sms_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSMSInboundAutomationsGetParams creates a new SMSInboundAutomationsGetParams object
// with the default values initialized.
func NewSMSInboundAutomationsGetParams() *SMSInboundAutomationsGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSInboundAutomationsGetParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewSMSInboundAutomationsGetParamsWithTimeout creates a new SMSInboundAutomationsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSMSInboundAutomationsGetParamsWithTimeout(timeout time.Duration) *SMSInboundAutomationsGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSInboundAutomationsGetParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		timeout: timeout,
	}
}

// NewSMSInboundAutomationsGetParamsWithContext creates a new SMSInboundAutomationsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSMSInboundAutomationsGetParamsWithContext(ctx context.Context) *SMSInboundAutomationsGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSInboundAutomationsGetParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		Context: ctx,
	}
}

// NewSMSInboundAutomationsGetParamsWithHTTPClient creates a new SMSInboundAutomationsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSMSInboundAutomationsGetParamsWithHTTPClient(client *http.Client) *SMSInboundAutomationsGetParams {
	var (
		limitDefault = int32(10)
		pageDefault  = int32(1)
	)
	return &SMSInboundAutomationsGetParams{
		Limit:      &limitDefault,
		Page:       &pageDefault,
		HTTPClient: client,
	}
}

/*SMSInboundAutomationsGetParams contains all the parameters to send to the API endpoint
for the Sms inbound automations get operation typically these are written to a http.Request
*/
type SMSInboundAutomationsGetParams struct {

	/*Limit
	  Number of records per page

	*/
	Limit *int32
	/*Page
	  Page number

	*/
	Page *int32
	/*Q
	  Your keyword or query.

	*/
	Q *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) WithTimeout(timeout time.Duration) *SMSInboundAutomationsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) WithContext(ctx context.Context) *SMSInboundAutomationsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) WithHTTPClient(client *http.Client) *SMSInboundAutomationsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) WithLimit(limit *int32) *SMSInboundAutomationsGetParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithPage adds the page to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) WithPage(page *int32) *SMSInboundAutomationsGetParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) SetPage(page *int32) {
	o.Page = page
}

// WithQ adds the q to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) WithQ(q *string) *SMSInboundAutomationsGetParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the Sms inbound automations get params
func (o *SMSInboundAutomationsGetParams) SetQ(q *string) {
	o.Q = q
}

// WriteToRequest writes these params to a swagger request
func (o *SMSInboundAutomationsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
