// Code generated by go-swagger; DO NOT EDIT.

package contact_list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListsByListIDGetParams creates a new ListsByListIDGetParams object
// with the default values initialized.
func NewListsByListIDGetParams() *ListsByListIDGetParams {
	var ()
	return &ListsByListIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListsByListIDGetParamsWithTimeout creates a new ListsByListIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListsByListIDGetParamsWithTimeout(timeout time.Duration) *ListsByListIDGetParams {
	var ()
	return &ListsByListIDGetParams{

		timeout: timeout,
	}
}

// NewListsByListIDGetParamsWithContext creates a new ListsByListIDGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewListsByListIDGetParamsWithContext(ctx context.Context) *ListsByListIDGetParams {
	var ()
	return &ListsByListIDGetParams{

		Context: ctx,
	}
}

// NewListsByListIDGetParamsWithHTTPClient creates a new ListsByListIDGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListsByListIDGetParamsWithHTTPClient(client *http.Client) *ListsByListIDGetParams {
	var ()
	return &ListsByListIDGetParams{
		HTTPClient: client,
	}
}

/*ListsByListIDGetParams contains all the parameters to send to the API endpoint
for the lists by list Id get operation typically these are written to a http.Request
*/
type ListsByListIDGetParams struct {

	/*ListID
	  List ID

	*/
	ListID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the lists by list Id get params
func (o *ListsByListIDGetParams) WithTimeout(timeout time.Duration) *ListsByListIDGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lists by list Id get params
func (o *ListsByListIDGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lists by list Id get params
func (o *ListsByListIDGetParams) WithContext(ctx context.Context) *ListsByListIDGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lists by list Id get params
func (o *ListsByListIDGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lists by list Id get params
func (o *ListsByListIDGetParams) WithHTTPClient(client *http.Client) *ListsByListIDGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lists by list Id get params
func (o *ListsByListIDGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithListID adds the listID to the lists by list Id get params
func (o *ListsByListIDGetParams) WithListID(listID int32) *ListsByListIDGetParams {
	o.SetListID(listID)
	return o
}

// SetListID adds the listId to the lists by list Id get params
func (o *ListsByListIDGetParams) SetListID(listID int32) {
	o.ListID = listID
}

// WriteToRequest writes these params to a swagger request
func (o *ListsByListIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param list_id
	if err := r.SetPathParam("list_id", swag.FormatInt32(o.ListID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
