// Code generated by go-swagger; DO NOT EDIT.

package post_return_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostReturnAddressesByReturnAddressIDDeleteReader is a Reader for the PostReturnAddressesByReturnAddressIDDelete structure.
type PostReturnAddressesByReturnAddressIDDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostReturnAddressesByReturnAddressIDDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostReturnAddressesByReturnAddressIDDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostReturnAddressesByReturnAddressIDDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostReturnAddressesByReturnAddressIDDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostReturnAddressesByReturnAddressIDDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostReturnAddressesByReturnAddressIDDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewPostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPostReturnAddressesByReturnAddressIDDeleteTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostReturnAddressesByReturnAddressIDDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostReturnAddressesByReturnAddressIDDeleteOK creates a PostReturnAddressesByReturnAddressIDDeleteOK with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteOK() *PostReturnAddressesByReturnAddressIDDeleteOK {
	return &PostReturnAddressesByReturnAddressIDDeleteOK{}
}

/*PostReturnAddressesByReturnAddressIDDeleteOK handles this case with default header values.

SUCCESS
*/
type PostReturnAddressesByReturnAddressIDDeleteOK struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteOK  %+v", 200, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteBadRequest creates a PostReturnAddressesByReturnAddressIDDeleteBadRequest with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteBadRequest() *PostReturnAddressesByReturnAddressIDDeleteBadRequest {
	return &PostReturnAddressesByReturnAddressIDDeleteBadRequest{}
}

/*PostReturnAddressesByReturnAddressIDDeleteBadRequest handles this case with default header values.

BAD_REQUEST
*/
type PostReturnAddressesByReturnAddressIDDeleteBadRequest struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteUnauthorized creates a PostReturnAddressesByReturnAddressIDDeleteUnauthorized with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteUnauthorized() *PostReturnAddressesByReturnAddressIDDeleteUnauthorized {
	return &PostReturnAddressesByReturnAddressIDDeleteUnauthorized{}
}

/*PostReturnAddressesByReturnAddressIDDeleteUnauthorized handles this case with default header values.

UNAUTHORIZED
*/
type PostReturnAddressesByReturnAddressIDDeleteUnauthorized struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteUnauthorized  %+v", 401, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteForbidden creates a PostReturnAddressesByReturnAddressIDDeleteForbidden with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteForbidden() *PostReturnAddressesByReturnAddressIDDeleteForbidden {
	return &PostReturnAddressesByReturnAddressIDDeleteForbidden{}
}

/*PostReturnAddressesByReturnAddressIDDeleteForbidden handles this case with default header values.

FORBIDDEN
*/
type PostReturnAddressesByReturnAddressIDDeleteForbidden struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteForbidden) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteForbidden  %+v", 403, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteNotFound creates a PostReturnAddressesByReturnAddressIDDeleteNotFound with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteNotFound() *PostReturnAddressesByReturnAddressIDDeleteNotFound {
	return &PostReturnAddressesByReturnAddressIDDeleteNotFound{}
}

/*PostReturnAddressesByReturnAddressIDDeleteNotFound handles this case with default header values.

NOT_FOUND
*/
type PostReturnAddressesByReturnAddressIDDeleteNotFound struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteNotFound  %+v", 404, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed creates a PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed() *PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed {
	return &PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed{}
}

/*PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed handles this case with default header values.

METHOD_NOT_FOUND
*/
type PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteTooManyRequests creates a PostReturnAddressesByReturnAddressIDDeleteTooManyRequests with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteTooManyRequests() *PostReturnAddressesByReturnAddressIDDeleteTooManyRequests {
	return &PostReturnAddressesByReturnAddressIDDeleteTooManyRequests{}
}

/*PostReturnAddressesByReturnAddressIDDeleteTooManyRequests handles this case with default header values.

TOO_MANY_REQUESTS
*/
type PostReturnAddressesByReturnAddressIDDeleteTooManyRequests struct {
	Payload interface{}
}

func (o *PostReturnAddressesByReturnAddressIDDeleteTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] postReturnAddressesByReturnAddressIdDeleteTooManyRequests  %+v", 429, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostReturnAddressesByReturnAddressIDDeleteDefault creates a PostReturnAddressesByReturnAddressIDDeleteDefault with default headers values
func NewPostReturnAddressesByReturnAddressIDDeleteDefault(code int) *PostReturnAddressesByReturnAddressIDDeleteDefault {
	return &PostReturnAddressesByReturnAddressIDDeleteDefault{
		_statusCode: code,
	}
}

/*PostReturnAddressesByReturnAddressIDDeleteDefault handles this case with default header values.

INTERNAL_SERVER_ERROR
*/
type PostReturnAddressesByReturnAddressIDDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the post return addresses by return address Id delete default response
func (o *PostReturnAddressesByReturnAddressIDDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PostReturnAddressesByReturnAddressIDDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /post/return-addresses/{return_address_id}][%d] PostReturnAddressesByReturnAddressIdDelete default  %+v", o._statusCode, o.Payload)
}

func (o *PostReturnAddressesByReturnAddressIDDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
