// Code generated by go-swagger; DO NOT EDIT.

package sms_campaign

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/danikarik/clicksend-go/models"
)

// NewSMSCampaignsSendPostParams creates a new SMSCampaignsSendPostParams object
// with the default values initialized.
func NewSMSCampaignsSendPostParams() *SMSCampaignsSendPostParams {
	var ()
	return &SMSCampaignsSendPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSMSCampaignsSendPostParamsWithTimeout creates a new SMSCampaignsSendPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSMSCampaignsSendPostParamsWithTimeout(timeout time.Duration) *SMSCampaignsSendPostParams {
	var ()
	return &SMSCampaignsSendPostParams{

		timeout: timeout,
	}
}

// NewSMSCampaignsSendPostParamsWithContext creates a new SMSCampaignsSendPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewSMSCampaignsSendPostParamsWithContext(ctx context.Context) *SMSCampaignsSendPostParams {
	var ()
	return &SMSCampaignsSendPostParams{

		Context: ctx,
	}
}

// NewSMSCampaignsSendPostParamsWithHTTPClient creates a new SMSCampaignsSendPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSMSCampaignsSendPostParamsWithHTTPClient(client *http.Client) *SMSCampaignsSendPostParams {
	var ()
	return &SMSCampaignsSendPostParams{
		HTTPClient: client,
	}
}

/*SMSCampaignsSendPostParams contains all the parameters to send to the API endpoint
for the Sms campaigns send post operation typically these are written to a http.Request
*/
type SMSCampaignsSendPostParams struct {

	/*Campaign
	  SmsCampaign model

	*/
	Campaign models.SMSCampaign

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) WithTimeout(timeout time.Duration) *SMSCampaignsSendPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) WithContext(ctx context.Context) *SMSCampaignsSendPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) WithHTTPClient(client *http.Client) *SMSCampaignsSendPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCampaign adds the campaign to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) WithCampaign(campaign models.SMSCampaign) *SMSCampaignsSendPostParams {
	o.SetCampaign(campaign)
	return o
}

// SetCampaign adds the campaign to the Sms campaigns send post params
func (o *SMSCampaignsSendPostParams) SetCampaign(campaign models.SMSCampaign) {
	o.Campaign = campaign
}

// WriteToRequest writes these params to a swagger request
func (o *SMSCampaignsSendPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Campaign); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
