// Code generated by go-swagger; DO NOT EDIT.

package email_marketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// EmailCampaignHistoryExportGetReader is a Reader for the EmailCampaignHistoryExportGet structure.
type EmailCampaignHistoryExportGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EmailCampaignHistoryExportGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEmailCampaignHistoryExportGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewEmailCampaignHistoryExportGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewEmailCampaignHistoryExportGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewEmailCampaignHistoryExportGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewEmailCampaignHistoryExportGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewEmailCampaignHistoryExportGetMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewEmailCampaignHistoryExportGetTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewEmailCampaignHistoryExportGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEmailCampaignHistoryExportGetOK creates a EmailCampaignHistoryExportGetOK with default headers values
func NewEmailCampaignHistoryExportGetOK() *EmailCampaignHistoryExportGetOK {
	return &EmailCampaignHistoryExportGetOK{}
}

/*EmailCampaignHistoryExportGetOK handles this case with default header values.

SUCCESS
*/
type EmailCampaignHistoryExportGetOK struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetOK) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetOK  %+v", 200, o.Payload)
}

func (o *EmailCampaignHistoryExportGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetBadRequest creates a EmailCampaignHistoryExportGetBadRequest with default headers values
func NewEmailCampaignHistoryExportGetBadRequest() *EmailCampaignHistoryExportGetBadRequest {
	return &EmailCampaignHistoryExportGetBadRequest{}
}

/*EmailCampaignHistoryExportGetBadRequest handles this case with default header values.

BAD_REQUEST
*/
type EmailCampaignHistoryExportGetBadRequest struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetBadRequest  %+v", 400, o.Payload)
}

func (o *EmailCampaignHistoryExportGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetUnauthorized creates a EmailCampaignHistoryExportGetUnauthorized with default headers values
func NewEmailCampaignHistoryExportGetUnauthorized() *EmailCampaignHistoryExportGetUnauthorized {
	return &EmailCampaignHistoryExportGetUnauthorized{}
}

/*EmailCampaignHistoryExportGetUnauthorized handles this case with default header values.

UNAUTHORIZED
*/
type EmailCampaignHistoryExportGetUnauthorized struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetUnauthorized  %+v", 401, o.Payload)
}

func (o *EmailCampaignHistoryExportGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetForbidden creates a EmailCampaignHistoryExportGetForbidden with default headers values
func NewEmailCampaignHistoryExportGetForbidden() *EmailCampaignHistoryExportGetForbidden {
	return &EmailCampaignHistoryExportGetForbidden{}
}

/*EmailCampaignHistoryExportGetForbidden handles this case with default header values.

FORBIDDEN
*/
type EmailCampaignHistoryExportGetForbidden struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetForbidden) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetForbidden  %+v", 403, o.Payload)
}

func (o *EmailCampaignHistoryExportGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetNotFound creates a EmailCampaignHistoryExportGetNotFound with default headers values
func NewEmailCampaignHistoryExportGetNotFound() *EmailCampaignHistoryExportGetNotFound {
	return &EmailCampaignHistoryExportGetNotFound{}
}

/*EmailCampaignHistoryExportGetNotFound handles this case with default header values.

NOT_FOUND
*/
type EmailCampaignHistoryExportGetNotFound struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetNotFound) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetNotFound  %+v", 404, o.Payload)
}

func (o *EmailCampaignHistoryExportGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetMethodNotAllowed creates a EmailCampaignHistoryExportGetMethodNotAllowed with default headers values
func NewEmailCampaignHistoryExportGetMethodNotAllowed() *EmailCampaignHistoryExportGetMethodNotAllowed {
	return &EmailCampaignHistoryExportGetMethodNotAllowed{}
}

/*EmailCampaignHistoryExportGetMethodNotAllowed handles this case with default header values.

METHOD_NOT_FOUND
*/
type EmailCampaignHistoryExportGetMethodNotAllowed struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *EmailCampaignHistoryExportGetMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetTooManyRequests creates a EmailCampaignHistoryExportGetTooManyRequests with default headers values
func NewEmailCampaignHistoryExportGetTooManyRequests() *EmailCampaignHistoryExportGetTooManyRequests {
	return &EmailCampaignHistoryExportGetTooManyRequests{}
}

/*EmailCampaignHistoryExportGetTooManyRequests handles this case with default header values.

TOO_MANY_REQUESTS
*/
type EmailCampaignHistoryExportGetTooManyRequests struct {
	Payload interface{}
}

func (o *EmailCampaignHistoryExportGetTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] emailCampaignHistoryExportGetTooManyRequests  %+v", 429, o.Payload)
}

func (o *EmailCampaignHistoryExportGetTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEmailCampaignHistoryExportGetDefault creates a EmailCampaignHistoryExportGetDefault with default headers values
func NewEmailCampaignHistoryExportGetDefault(code int) *EmailCampaignHistoryExportGetDefault {
	return &EmailCampaignHistoryExportGetDefault{
		_statusCode: code,
	}
}

/*EmailCampaignHistoryExportGetDefault handles this case with default header values.

INTERNAL_SERVER_ERROR
*/
type EmailCampaignHistoryExportGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the email campaign history export get default response
func (o *EmailCampaignHistoryExportGetDefault) Code() int {
	return o._statusCode
}

func (o *EmailCampaignHistoryExportGetDefault) Error() string {
	return fmt.Sprintf("[GET /email-campaigns/{email_campaign_id}/history/export][%d] EmailCampaignHistoryExportGet default  %+v", o._statusCode, o.Payload)
}

func (o *EmailCampaignHistoryExportGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
