// Code generated by go-swagger; DO NOT EDIT.

package email_marketing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVerifyAllowedEmailAddressGetParams creates a new VerifyAllowedEmailAddressGetParams object
// with the default values initialized.
func NewVerifyAllowedEmailAddressGetParams() *VerifyAllowedEmailAddressGetParams {
	var ()
	return &VerifyAllowedEmailAddressGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVerifyAllowedEmailAddressGetParamsWithTimeout creates a new VerifyAllowedEmailAddressGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVerifyAllowedEmailAddressGetParamsWithTimeout(timeout time.Duration) *VerifyAllowedEmailAddressGetParams {
	var ()
	return &VerifyAllowedEmailAddressGetParams{

		timeout: timeout,
	}
}

// NewVerifyAllowedEmailAddressGetParamsWithContext creates a new VerifyAllowedEmailAddressGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewVerifyAllowedEmailAddressGetParamsWithContext(ctx context.Context) *VerifyAllowedEmailAddressGetParams {
	var ()
	return &VerifyAllowedEmailAddressGetParams{

		Context: ctx,
	}
}

// NewVerifyAllowedEmailAddressGetParamsWithHTTPClient creates a new VerifyAllowedEmailAddressGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewVerifyAllowedEmailAddressGetParamsWithHTTPClient(client *http.Client) *VerifyAllowedEmailAddressGetParams {
	var ()
	return &VerifyAllowedEmailAddressGetParams{
		HTTPClient: client,
	}
}

/*VerifyAllowedEmailAddressGetParams contains all the parameters to send to the API endpoint
for the verify allowed email address get operation typically these are written to a http.Request
*/
type VerifyAllowedEmailAddressGetParams struct {

	/*ActivationToken
	  Your activation token.

	*/
	ActivationToken string
	/*EmailAddressID
	  Allowed email address id

	*/
	EmailAddressID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) WithTimeout(timeout time.Duration) *VerifyAllowedEmailAddressGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) WithContext(ctx context.Context) *VerifyAllowedEmailAddressGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) WithHTTPClient(client *http.Client) *VerifyAllowedEmailAddressGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivationToken adds the activationToken to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) WithActivationToken(activationToken string) *VerifyAllowedEmailAddressGetParams {
	o.SetActivationToken(activationToken)
	return o
}

// SetActivationToken adds the activationToken to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) SetActivationToken(activationToken string) {
	o.ActivationToken = activationToken
}

// WithEmailAddressID adds the emailAddressID to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) WithEmailAddressID(emailAddressID int32) *VerifyAllowedEmailAddressGetParams {
	o.SetEmailAddressID(emailAddressID)
	return o
}

// SetEmailAddressID adds the emailAddressId to the verify allowed email address get params
func (o *VerifyAllowedEmailAddressGetParams) SetEmailAddressID(emailAddressID int32) {
	o.EmailAddressID = emailAddressID
}

// WriteToRequest writes these params to a swagger request
func (o *VerifyAllowedEmailAddressGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activation_token
	if err := r.SetPathParam("activation_token", o.ActivationToken); err != nil {
		return err
	}

	// path param email_address_id
	if err := r.SetPathParam("email_address_id", swag.FormatInt32(o.EmailAddressID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
