// Code generated by go-swagger; DO NOT EDIT.

package mms_campaign

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MMSCampaignsGetReader is a Reader for the MMSCampaignsGet structure.
type MMSCampaignsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MMSCampaignsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMMSCampaignsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewMMSCampaignsGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewMMSCampaignsGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewMMSCampaignsGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewMMSCampaignsGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewMMSCampaignsGetMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewMMSCampaignsGetTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewMMSCampaignsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMMSCampaignsGetOK creates a MMSCampaignsGetOK with default headers values
func NewMMSCampaignsGetOK() *MMSCampaignsGetOK {
	return &MMSCampaignsGetOK{}
}

/*MMSCampaignsGetOK handles this case with default header values.

SUCCESS
*/
type MMSCampaignsGetOK struct {
	Payload interface{}
}

func (o *MMSCampaignsGetOK) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetOK  %+v", 200, o.Payload)
}

func (o *MMSCampaignsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetBadRequest creates a MMSCampaignsGetBadRequest with default headers values
func NewMMSCampaignsGetBadRequest() *MMSCampaignsGetBadRequest {
	return &MMSCampaignsGetBadRequest{}
}

/*MMSCampaignsGetBadRequest handles this case with default header values.

BAD_REQUEST
*/
type MMSCampaignsGetBadRequest struct {
	Payload interface{}
}

func (o *MMSCampaignsGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetBadRequest  %+v", 400, o.Payload)
}

func (o *MMSCampaignsGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetUnauthorized creates a MMSCampaignsGetUnauthorized with default headers values
func NewMMSCampaignsGetUnauthorized() *MMSCampaignsGetUnauthorized {
	return &MMSCampaignsGetUnauthorized{}
}

/*MMSCampaignsGetUnauthorized handles this case with default header values.

UNAUTHORIZED
*/
type MMSCampaignsGetUnauthorized struct {
	Payload interface{}
}

func (o *MMSCampaignsGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetUnauthorized  %+v", 401, o.Payload)
}

func (o *MMSCampaignsGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetForbidden creates a MMSCampaignsGetForbidden with default headers values
func NewMMSCampaignsGetForbidden() *MMSCampaignsGetForbidden {
	return &MMSCampaignsGetForbidden{}
}

/*MMSCampaignsGetForbidden handles this case with default header values.

FORBIDDEN
*/
type MMSCampaignsGetForbidden struct {
	Payload interface{}
}

func (o *MMSCampaignsGetForbidden) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetForbidden  %+v", 403, o.Payload)
}

func (o *MMSCampaignsGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetNotFound creates a MMSCampaignsGetNotFound with default headers values
func NewMMSCampaignsGetNotFound() *MMSCampaignsGetNotFound {
	return &MMSCampaignsGetNotFound{}
}

/*MMSCampaignsGetNotFound handles this case with default header values.

NOT_FOUND
*/
type MMSCampaignsGetNotFound struct {
	Payload interface{}
}

func (o *MMSCampaignsGetNotFound) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetNotFound  %+v", 404, o.Payload)
}

func (o *MMSCampaignsGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetMethodNotAllowed creates a MMSCampaignsGetMethodNotAllowed with default headers values
func NewMMSCampaignsGetMethodNotAllowed() *MMSCampaignsGetMethodNotAllowed {
	return &MMSCampaignsGetMethodNotAllowed{}
}

/*MMSCampaignsGetMethodNotAllowed handles this case with default header values.

METHOD_NOT_FOUND
*/
type MMSCampaignsGetMethodNotAllowed struct {
	Payload interface{}
}

func (o *MMSCampaignsGetMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *MMSCampaignsGetMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetTooManyRequests creates a MMSCampaignsGetTooManyRequests with default headers values
func NewMMSCampaignsGetTooManyRequests() *MMSCampaignsGetTooManyRequests {
	return &MMSCampaignsGetTooManyRequests{}
}

/*MMSCampaignsGetTooManyRequests handles this case with default header values.

TOO_MANY_REQUESTS
*/
type MMSCampaignsGetTooManyRequests struct {
	Payload interface{}
}

func (o *MMSCampaignsGetTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] mmsCampaignsGetTooManyRequests  %+v", 429, o.Payload)
}

func (o *MMSCampaignsGetTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignsGetDefault creates a MMSCampaignsGetDefault with default headers values
func NewMMSCampaignsGetDefault(code int) *MMSCampaignsGetDefault {
	return &MMSCampaignsGetDefault{
		_statusCode: code,
	}
}

/*MMSCampaignsGetDefault handles this case with default header values.

INTERNAL_SERVER_ERROR
*/
type MMSCampaignsGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the Mms campaigns get default response
func (o *MMSCampaignsGetDefault) Code() int {
	return o._statusCode
}

func (o *MMSCampaignsGetDefault) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns][%d] MmsCampaignsGet default  %+v", o._statusCode, o.Payload)
}

func (o *MMSCampaignsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
