// Code generated by go-swagger; DO NOT EDIT.

package mms_campaign

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// MMSCampaignByMMSCampaignIDGetReader is a Reader for the MMSCampaignByMMSCampaignIDGet structure.
type MMSCampaignByMMSCampaignIDGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MMSCampaignByMMSCampaignIDGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewMMSCampaignByMMSCampaignIDGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewMMSCampaignByMMSCampaignIDGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewMMSCampaignByMMSCampaignIDGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewMMSCampaignByMMSCampaignIDGetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewMMSCampaignByMMSCampaignIDGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewMMSCampaignByMMSCampaignIDGetMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewMMSCampaignByMMSCampaignIDGetTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewMMSCampaignByMMSCampaignIDGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewMMSCampaignByMMSCampaignIDGetOK creates a MMSCampaignByMMSCampaignIDGetOK with default headers values
func NewMMSCampaignByMMSCampaignIDGetOK() *MMSCampaignByMMSCampaignIDGetOK {
	return &MMSCampaignByMMSCampaignIDGetOK{}
}

/*MMSCampaignByMMSCampaignIDGetOK handles this case with default header values.

SUCCESS
*/
type MMSCampaignByMMSCampaignIDGetOK struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetOK) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetOK  %+v", 200, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetBadRequest creates a MMSCampaignByMMSCampaignIDGetBadRequest with default headers values
func NewMMSCampaignByMMSCampaignIDGetBadRequest() *MMSCampaignByMMSCampaignIDGetBadRequest {
	return &MMSCampaignByMMSCampaignIDGetBadRequest{}
}

/*MMSCampaignByMMSCampaignIDGetBadRequest handles this case with default header values.

BAD_REQUEST
*/
type MMSCampaignByMMSCampaignIDGetBadRequest struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetBadRequest  %+v", 400, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetUnauthorized creates a MMSCampaignByMMSCampaignIDGetUnauthorized with default headers values
func NewMMSCampaignByMMSCampaignIDGetUnauthorized() *MMSCampaignByMMSCampaignIDGetUnauthorized {
	return &MMSCampaignByMMSCampaignIDGetUnauthorized{}
}

/*MMSCampaignByMMSCampaignIDGetUnauthorized handles this case with default header values.

UNAUTHORIZED
*/
type MMSCampaignByMMSCampaignIDGetUnauthorized struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetUnauthorized  %+v", 401, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetForbidden creates a MMSCampaignByMMSCampaignIDGetForbidden with default headers values
func NewMMSCampaignByMMSCampaignIDGetForbidden() *MMSCampaignByMMSCampaignIDGetForbidden {
	return &MMSCampaignByMMSCampaignIDGetForbidden{}
}

/*MMSCampaignByMMSCampaignIDGetForbidden handles this case with default header values.

FORBIDDEN
*/
type MMSCampaignByMMSCampaignIDGetForbidden struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetForbidden) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetForbidden  %+v", 403, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetNotFound creates a MMSCampaignByMMSCampaignIDGetNotFound with default headers values
func NewMMSCampaignByMMSCampaignIDGetNotFound() *MMSCampaignByMMSCampaignIDGetNotFound {
	return &MMSCampaignByMMSCampaignIDGetNotFound{}
}

/*MMSCampaignByMMSCampaignIDGetNotFound handles this case with default header values.

NOT_FOUND
*/
type MMSCampaignByMMSCampaignIDGetNotFound struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetNotFound) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetNotFound  %+v", 404, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetMethodNotAllowed creates a MMSCampaignByMMSCampaignIDGetMethodNotAllowed with default headers values
func NewMMSCampaignByMMSCampaignIDGetMethodNotAllowed() *MMSCampaignByMMSCampaignIDGetMethodNotAllowed {
	return &MMSCampaignByMMSCampaignIDGetMethodNotAllowed{}
}

/*MMSCampaignByMMSCampaignIDGetMethodNotAllowed handles this case with default header values.

METHOD_NOT_FOUND
*/
type MMSCampaignByMMSCampaignIDGetMethodNotAllowed struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetMethodNotAllowed) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetTooManyRequests creates a MMSCampaignByMMSCampaignIDGetTooManyRequests with default headers values
func NewMMSCampaignByMMSCampaignIDGetTooManyRequests() *MMSCampaignByMMSCampaignIDGetTooManyRequests {
	return &MMSCampaignByMMSCampaignIDGetTooManyRequests{}
}

/*MMSCampaignByMMSCampaignIDGetTooManyRequests handles this case with default header values.

TOO_MANY_REQUESTS
*/
type MMSCampaignByMMSCampaignIDGetTooManyRequests struct {
	Payload interface{}
}

func (o *MMSCampaignByMMSCampaignIDGetTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] mmsCampaignByMmsCampaignIdGetTooManyRequests  %+v", 429, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMMSCampaignByMMSCampaignIDGetDefault creates a MMSCampaignByMMSCampaignIDGetDefault with default headers values
func NewMMSCampaignByMMSCampaignIDGetDefault(code int) *MMSCampaignByMMSCampaignIDGetDefault {
	return &MMSCampaignByMMSCampaignIDGetDefault{
		_statusCode: code,
	}
}

/*MMSCampaignByMMSCampaignIDGetDefault handles this case with default header values.

INTERNAL_SERVER_ERROR
*/
type MMSCampaignByMMSCampaignIDGetDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the Mms campaign by Mms campaign Id get default response
func (o *MMSCampaignByMMSCampaignIDGetDefault) Code() int {
	return o._statusCode
}

func (o *MMSCampaignByMMSCampaignIDGetDefault) Error() string {
	return fmt.Sprintf("[GET /mms-campaigns/{mms_campaign_id}][%d] MmsCampaignByMmsCampaignIdGet default  %+v", o._statusCode, o.Payload)
}

func (o *MMSCampaignByMMSCampaignIDGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
