// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"io"
	"io/ioutil"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"
)

// EmailTemplateUpdate Model for Email Templates
// swagger:discriminator EmailTemplateUpdate classType
type EmailTemplateUpdate interface {
	runtime.Validatable

	// Your template body.
	// Required: true
	Body() *string
	SetBody(*string)

	// The intended name for the template.
	TemplateName() string
	SetTemplateName(string)
}

type emailTemplateUpdate struct {
	bodyField *string

	templateNameField string
}

// Body gets the body of this polymorphic type
func (m *emailTemplateUpdate) Body() *string {
	return m.bodyField
}

// SetBody sets the body of this polymorphic type
func (m *emailTemplateUpdate) SetBody(val *string) {
	m.bodyField = val
}

// TemplateName gets the template name of this polymorphic type
func (m *emailTemplateUpdate) TemplateName() string {
	return m.templateNameField
}

// SetTemplateName sets the template name of this polymorphic type
func (m *emailTemplateUpdate) SetTemplateName(val string) {
	m.templateNameField = val
}

// UnmarshalEmailTemplateUpdateSlice unmarshals polymorphic slices of EmailTemplateUpdate
func UnmarshalEmailTemplateUpdateSlice(reader io.Reader, consumer runtime.Consumer) ([]EmailTemplateUpdate, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []EmailTemplateUpdate
	for _, element := range elements {
		obj, err := unmarshalEmailTemplateUpdate(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalEmailTemplateUpdate unmarshals polymorphic EmailTemplateUpdate
func UnmarshalEmailTemplateUpdate(reader io.Reader, consumer runtime.Consumer) (EmailTemplateUpdate, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalEmailTemplateUpdate(data, consumer)
}

func unmarshalEmailTemplateUpdate(data []byte, consumer runtime.Consumer) (EmailTemplateUpdate, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the classType property.
	var getType struct {
		ClassType string `json:"classType"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("classType", "body", getType.ClassType); err != nil {
		return nil, err
	}

	// The value of classType is used to determine which type to create and unmarshal the data into
	switch getType.ClassType {
	case "EmailTemplateUpdate":
		var result emailTemplateUpdate
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil

	}
	return nil, errors.New(422, "invalid classType value: %q", getType.ClassType)

}

// Validate validates this email template update
func (m *emailTemplateUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *emailTemplateUpdate) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body()); err != nil {
		return err
	}

	return nil
}
