// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"io"
	"io/ioutil"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"
)

// MMSMessage Single MMS message model
// swagger:discriminator MmsMessage classType
type MMSMessage interface {
	runtime.Validatable

	// Your message
	// Required: true
	Body() *string
	SetBody(*string)

	// Recipient country
	Country() string
	SetCountry(string)

	// Custom string for your reference
	CustomString() string
	SetCustomString(string)

	// Your sender ID
	From() string
	SetFrom(string)

	// Email to send replies to
	FromEmail() string
	SetFromEmail(string)

	// Your list ID if sending to a whole list (can be used instead of 'to')
	ListID() int32
	SetListID(int32)

	// Schedule time in unix format (leave blank for immediate delivery)
	Schedule() int32
	SetSchedule(int32)

	// Your method of sending
	Source() *string
	SetSource(*string)

	// Subject line (max 20 characters)
	// Required: true
	Subject() *string
	SetSubject(*string)

	// Recipient phone number in E.164 format
	// Required: true
	To() *string
	SetTo(*string)
}

type mmsMessage struct {
	bodyField *string

	countryField string

	customStringField string

	fromField string

	fromEmailField string

	listIdField int32

	scheduleField int32

	sourceField *string

	subjectField *string

	toField *string
}

// Body gets the body of this polymorphic type
func (m *mmsMessage) Body() *string {
	return m.bodyField
}

// SetBody sets the body of this polymorphic type
func (m *mmsMessage) SetBody(val *string) {
	m.bodyField = val
}

// Country gets the country of this polymorphic type
func (m *mmsMessage) Country() string {
	return m.countryField
}

// SetCountry sets the country of this polymorphic type
func (m *mmsMessage) SetCountry(val string) {
	m.countryField = val
}

// CustomString gets the custom string of this polymorphic type
func (m *mmsMessage) CustomString() string {
	return m.customStringField
}

// SetCustomString sets the custom string of this polymorphic type
func (m *mmsMessage) SetCustomString(val string) {
	m.customStringField = val
}

// From gets the from of this polymorphic type
func (m *mmsMessage) From() string {
	return m.fromField
}

// SetFrom sets the from of this polymorphic type
func (m *mmsMessage) SetFrom(val string) {
	m.fromField = val
}

// FromEmail gets the from email of this polymorphic type
func (m *mmsMessage) FromEmail() string {
	return m.fromEmailField
}

// SetFromEmail sets the from email of this polymorphic type
func (m *mmsMessage) SetFromEmail(val string) {
	m.fromEmailField = val
}

// ListID gets the list id of this polymorphic type
func (m *mmsMessage) ListID() int32 {
	return m.listIdField
}

// SetListID sets the list id of this polymorphic type
func (m *mmsMessage) SetListID(val int32) {
	m.listIdField = val
}

// Schedule gets the schedule of this polymorphic type
func (m *mmsMessage) Schedule() int32 {
	return m.scheduleField
}

// SetSchedule sets the schedule of this polymorphic type
func (m *mmsMessage) SetSchedule(val int32) {
	m.scheduleField = val
}

// Source gets the source of this polymorphic type
func (m *mmsMessage) Source() *string {
	return m.sourceField
}

// SetSource sets the source of this polymorphic type
func (m *mmsMessage) SetSource(val *string) {
	m.sourceField = val
}

// Subject gets the subject of this polymorphic type
func (m *mmsMessage) Subject() *string {
	return m.subjectField
}

// SetSubject sets the subject of this polymorphic type
func (m *mmsMessage) SetSubject(val *string) {
	m.subjectField = val
}

// To gets the to of this polymorphic type
func (m *mmsMessage) To() *string {
	return m.toField
}

// SetTo sets the to of this polymorphic type
func (m *mmsMessage) SetTo(val *string) {
	m.toField = val
}

// UnmarshalMMSMessageSlice unmarshals polymorphic slices of MMSMessage
func UnmarshalMMSMessageSlice(reader io.Reader, consumer runtime.Consumer) ([]MMSMessage, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []MMSMessage
	for _, element := range elements {
		obj, err := unmarshalMMSMessage(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalMMSMessage unmarshals polymorphic MMSMessage
func UnmarshalMMSMessage(reader io.Reader, consumer runtime.Consumer) (MMSMessage, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalMMSMessage(data, consumer)
}

func unmarshalMMSMessage(data []byte, consumer runtime.Consumer) (MMSMessage, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the classType property.
	var getType struct {
		ClassType string `json:"classType"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("classType", "body", getType.ClassType); err != nil {
		return nil, err
	}

	// The value of classType is used to determine which type to create and unmarshal the data into
	switch getType.ClassType {
	case "MmsMessage":
		var result mmsMessage
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil

	}
	return nil, errors.New(422, "invalid classType value: %q", getType.ClassType)

}

// Validate validates this Mms message
func (m *mmsMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *mmsMessage) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body()); err != nil {
		return err
	}

	return nil
}

func (m *mmsMessage) validateSubject(formats strfmt.Registry) error {

	if err := validate.Required("subject", "body", m.Subject()); err != nil {
		return err
	}

	return nil
}

func (m *mmsMessage) validateTo(formats strfmt.Registry) error {

	if err := validate.Required("to", "body", m.To()); err != nil {
		return err
	}

	return nil
}
