// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"encoding/json"
	"io"
	"io/ioutil"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"
)

// SMSMessage SmsMessage model
// swagger:discriminator SmsMessage classType
type SMSMessage interface {
	runtime.Validatable

	// Your message.
	// Required: true
	Body() *string
	SetBody(*string)

	// Recipient country.
	Country() string
	SetCountry(string)

	// Your reference. Will be passed back with all replies and delivery reports.
	CustomString() string
	SetCustomString(string)

	// Your sender id - more info: http://help.clicksend.com/SMS/what-is-a-sender-id-or-sender-number.
	From() string
	SetFrom(string)

	// An email address where the reply should be emailed to. If omitted, the reply will be emailed back to the user who sent the outgoing SMS.
	FromEmail() string
	SetFromEmail(string)

	// Your list ID if sending to a whole list. Can be used instead of 'to'.
	ListID() int32
	SetListID(int32)

	// Leave blank for immediate delivery. Your schedule time in unix format http://help.clicksend.com/what-is-a-unix-timestamp
	Schedule() int32
	SetSchedule(int32)

	// Your method of sending e.g. 'wordpress', 'php', 'c#'.
	Source() *string
	SetSource(*string)

	// Recipient phone number in E.164 format.
	// Required: true
	To() *string
	SetTo(*string)
}

type smsMessage struct {
	bodyField *string

	countryField string

	customStringField string

	fromField string

	fromEmailField string

	listIdField int32

	scheduleField int32

	sourceField *string

	toField *string
}

// Body gets the body of this polymorphic type
func (m *smsMessage) Body() *string {
	return m.bodyField
}

// SetBody sets the body of this polymorphic type
func (m *smsMessage) SetBody(val *string) {
	m.bodyField = val
}

// Country gets the country of this polymorphic type
func (m *smsMessage) Country() string {
	return m.countryField
}

// SetCountry sets the country of this polymorphic type
func (m *smsMessage) SetCountry(val string) {
	m.countryField = val
}

// CustomString gets the custom string of this polymorphic type
func (m *smsMessage) CustomString() string {
	return m.customStringField
}

// SetCustomString sets the custom string of this polymorphic type
func (m *smsMessage) SetCustomString(val string) {
	m.customStringField = val
}

// From gets the from of this polymorphic type
func (m *smsMessage) From() string {
	return m.fromField
}

// SetFrom sets the from of this polymorphic type
func (m *smsMessage) SetFrom(val string) {
	m.fromField = val
}

// FromEmail gets the from email of this polymorphic type
func (m *smsMessage) FromEmail() string {
	return m.fromEmailField
}

// SetFromEmail sets the from email of this polymorphic type
func (m *smsMessage) SetFromEmail(val string) {
	m.fromEmailField = val
}

// ListID gets the list id of this polymorphic type
func (m *smsMessage) ListID() int32 {
	return m.listIdField
}

// SetListID sets the list id of this polymorphic type
func (m *smsMessage) SetListID(val int32) {
	m.listIdField = val
}

// Schedule gets the schedule of this polymorphic type
func (m *smsMessage) Schedule() int32 {
	return m.scheduleField
}

// SetSchedule sets the schedule of this polymorphic type
func (m *smsMessage) SetSchedule(val int32) {
	m.scheduleField = val
}

// Source gets the source of this polymorphic type
func (m *smsMessage) Source() *string {
	return m.sourceField
}

// SetSource sets the source of this polymorphic type
func (m *smsMessage) SetSource(val *string) {
	m.sourceField = val
}

// To gets the to of this polymorphic type
func (m *smsMessage) To() *string {
	return m.toField
}

// SetTo sets the to of this polymorphic type
func (m *smsMessage) SetTo(val *string) {
	m.toField = val
}

// UnmarshalSMSMessageSlice unmarshals polymorphic slices of SMSMessage
func UnmarshalSMSMessageSlice(reader io.Reader, consumer runtime.Consumer) ([]SMSMessage, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []SMSMessage
	for _, element := range elements {
		obj, err := unmarshalSMSMessage(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalSMSMessage unmarshals polymorphic SMSMessage
func UnmarshalSMSMessage(reader io.Reader, consumer runtime.Consumer) (SMSMessage, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalSMSMessage(data, consumer)
}

func unmarshalSMSMessage(data []byte, consumer runtime.Consumer) (SMSMessage, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the classType property.
	var getType struct {
		ClassType string `json:"classType"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("classType", "body", getType.ClassType); err != nil {
		return nil, err
	}

	// The value of classType is used to determine which type to create and unmarshal the data into
	switch getType.ClassType {
	case "SmsMessage":
		var result smsMessage
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil

	}
	return nil, errors.New(422, "invalid classType value: %q", getType.ClassType)

}

// Validate validates this Sms message
func (m *smsMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *smsMessage) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body()); err != nil {
		return err
	}

	return nil
}

func (m *smsMessage) validateTo(formats strfmt.Registry) error {

	if err := validate.Required("to", "body", m.To()); err != nil {
		return err
	}

	return nil
}
